import { prisma } from "../models/prisma.js";
import { logActivity } from "./activity.js";
import { expiryReminderEmail, rentDueReminderEmail } from "./gmail.js";
import { computeLeaseEndDate } from "./lease-timeline-shared.js";

// Every agreement clause set generated by this app states rent is "payable by
// the 5th" (see services/agreement.js) — there's no per-listing due-day
// field, so this mirrors that same fixed convention rather than inventing a
// second, disconnected one.
const RENT_DUE_DAY = 5;
const DAY_MS = 24 * 60 * 60 * 1000;

function startOfDay(d) {
  return new Date(d.getFullYear(), d.getMonth(), d.getDate());
}

function daysBetween(a, b) {
  return Math.round((startOfDay(b).getTime() - startOfDay(a).getTime()) / DAY_MS);
}

function monthLabel(d) {
  return d.toLocaleString("en-US", { month: "long", year: "numeric" });
}

// ReminderRunSummary = { expiry30Sent, expiry7Sent, rentDueSent, checkedAgreements, checkedTenancies }

/**
 * Scans for two independent things and sends whichever reminders are due
 * today: agreements 30/7 days from expiry, and active tenancies 3 days from
 * their next rent-due date. Meant to be invoked on a recurring schedule (see
 * /api/cron/reminders) — every send is guarded so re-running this on the same
 * day, or every day within a window, never re-sends the same reminder twice.
 */
export async function runScheduledReminders(now = new Date()) {
  const summary = {
    expiry30Sent: 0,
    expiry7Sent: 0,
    rentDueSent: 0,
    checkedAgreements: 0,
    checkedTenancies: 0,
  };

  // ── Agreement expiry: 30 and 7 days out ──────────────────────────────────
  const signedDrafts = await prisma.agreementDraft.findMany({
    where: {
      tenantSignature: { not: null },
      landlordSignature: { not: null },
      profile: { accountType: "tenant" },
    },
    include: { profile: { include: { user: true } } },
  });

  for (const draft of signedDrafts) {
    const listingId = draft.reference.split("/")[0];
    if (!listingId) continue;
    const terms = draft.termsJson;
    const durationMonths = terms?.durationMonths;
    if (!durationMonths) continue;

    const [listing, application] = await Promise.all([
      prisma.listing.findUnique({ where: { id: listingId } }),
      prisma.application.findUnique({
        where: { profileId_listingId: { profileId: draft.profileId, listingId } },
      }),
    ]);
    if (!listing || !application || application.status !== "accepted") continue;

    summary.checkedAgreements++;
    const endDate = computeLeaseEndDate(listing.availableFrom, durationMonths);
    const daysOut = daysBetween(now, endDate);
    const endDateLabel = endDate.toLocaleDateString("en-GB", {
      day: "numeric",
      month: "long",
      year: "numeric",
    });

    if (daysOut === 30 && !draft.expiry30ReminderSentAt) {
      if (draft.profile.user.email) {
        await expiryReminderEmail(
          draft.profile.user.email,
          draft.profile.displayName,
          endDateLabel,
        ).catch(() => {});
      }
      await prisma.agreementDraft.update({
        where: { id: draft.id },
        data: { expiry30ReminderSentAt: now },
      });
      await logActivity({
        listingId,
        tenantProfileId: draft.profileId,
        type: "expiry_reminder_sent",
        actor: "system",
        summary: `30-day agreement expiry reminder sent (Ref ${draft.reference}, expires ${endDateLabel}).`,
        metadata: { daysOut: 30, reference: draft.reference },
      });
      summary.expiry30Sent++;
    } else if (daysOut === 7 && !draft.expiry7ReminderSentAt) {
      if (draft.profile.user.email) {
        await expiryReminderEmail(
          draft.profile.user.email,
          draft.profile.displayName,
          endDateLabel,
        ).catch(() => {});
      }
      await prisma.agreementDraft.update({
        where: { id: draft.id },
        data: { expiry7ReminderSentAt: now },
      });
      await logActivity({
        listingId,
        tenantProfileId: draft.profileId,
        type: "expiry_reminder_sent",
        actor: "system",
        summary: `7-day agreement expiry reminder sent (Ref ${draft.reference}, expires ${endDateLabel}).`,
        metadata: { daysOut: 7, reference: draft.reference },
      });
      summary.expiry7Sent++;
    }
  }

  // ── Rent due in 3 days ────────────────────────────────────────────────────
  const dueDateThisMonth = new Date(now.getFullYear(), now.getMonth(), RENT_DUE_DAY);
  const daysToDue = daysBetween(now, dueDateThisMonth);

  if (daysToDue === 3) {
    const currentMonthLabel = monthLabel(dueDateThisMonth);
    const activeApplications = await prisma.application.findMany({
      where: { status: "accepted" },
      include: { profile: { include: { user: true } }, listing: true },
    });

    for (const app of activeApplications) {
      summary.checkedTenancies++;
      const [paidThisMonth, alreadyReminded] = await Promise.all([
        prisma.payment.findFirst({
          where: {
            listingId: app.listingId,
            profileId: app.profileId,
            month: currentMonthLabel,
            status: "paid",
          },
        }),
        prisma.activityEvent.findFirst({
          where: {
            listingId: app.listingId,
            tenantProfileId: app.profileId,
            type: "rent_due_reminder_sent",
            metadata: { path: ["month"], equals: currentMonthLabel },
          },
        }),
      ]);
      if (paidThisMonth || alreadyReminded) continue;

      if (app.profile.user.email) {
        await rentDueReminderEmail(
          app.profile.user.email,
          app.profile.displayName,
          app.listing.title,
          currentMonthLabel,
        ).catch(() => {});
      }
      await logActivity({
        listingId: app.listingId,
        tenantProfileId: app.profileId,
        type: "rent_due_reminder_sent",
        actor: "system",
        summary: `Rent-due reminder sent for ${currentMonthLabel} (due the ${RENT_DUE_DAY}${RENT_DUE_DAY === 5 ? "th" : ""}).`,
        metadata: { month: currentMonthLabel },
      });
      summary.rentDueSent++;
    }
  }

  return summary;
}
